### PR TITLE
Small typos fixes

### PR DESCRIPTION
**Pull request by xvrdm**
Thanks a lot for the awesome themes, haven't looked back since I started using them!

### CODE REVIEW

**Comment by hrbrmstr** [comment]
Many thanks! _But_ no fix is "small". You took the time to make the package better! If you have time, please update the PR and add yourself as a contributor to the DESCRIPTION in the `Authors@R` section. I'll try to get to it this weekend (trust me, I know all-too-well abt time being sparse :-)

thx again for the fix!

**Comment by xvrdm** [comment]
Hi Bob, sorry to use this completely inadequate mean to reach you. I could not find anything else. 

Just realized that you blocked me on Twitter. If i have done something offending, I would probably be happy to apologize. If that’s an error, i would be happy to see them again since I found a lot of great stuff in them over the years. I wont insist after this message. 

Kind regards

**Comment by hrbrmstr** [comment]
(I rly need to have a canned response for this :-)

Was not an "active" block. I'm part of a 3 "block together" networks and they are getting more abused by folks (i.e. I've been seeing a trend of them being used maliciously — i.e. not to block pornographic accounts or evil/ill-intent bots but folks are using them to get innocent folks like you on the list for some reason.

Before becoming part of those block-together networks I was abt to leave twitter due to the spam levels (and rly horrible content they were spewing at my account). but this is now the 10th "you've blocked me" this year and all 10 have been unwarranted. I'll unblock and follow so it can't happen again.

**Comment by xvrdm** [comment]
Thanks a lot, I did not know that "shared block lists" were a thing. 

I guess settings like ["block anybody mentioning me with less than 15 followers"](https://blocktogether.org/) might work well but are also a bit problematic for newcomers. Maybe there are not really good solutions yet to the problem.

**Pull request closed without merging**
